name: Check if Downdetector is down
on: 
  push:
    branches: [chron-curl]
  pull_request:
    branches: [chron-curl]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        id: curlDownDet
        run: |
          status_code=$(curl -sL -w  "%{http_code}" "https://downdetector.com" -o >(cat >/tmp/curl_body))
          echo "RESPONSE::: $status_code"
      - name: value out of scope
        run: echo "${{ steps.curlDownDet.status_code }}"
      - name: DownIsDown
        if: steps.curlDownDet.status_code != 200 
        run: echo ${{steps.curlDownDet.status_code}}
      - name: Not Down
        if: steps.curlDownDet.status_code == 200 
        run: echo "All is Well"