name: Check if Downdetector is down
on: 
  push:
    branches: [chron-curl]
  pull_request:
    branches: [chron-curl]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        id: curlDownDet
        run: |
          status_code=$(curl -sL -w  "%(http_code)\\n" "https://downdetector.com" -o/dev/null)
          echo ${{ steps.curlDownDet.status_code }}
      - name: NotDown
        if: steps.curlDownDet.status_code != 200 
        run: echo "Down Detector is Down!!"
      - name: DownIsDown
        if: steps.curlDownDet.status_code == 200 
        run: echo "All is Well"