name: Check if Downdetector is down
on: 
  push:
    branches: [curl-website]
  pull_request:
    branches: [curl-website]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        id: curlDownDet
        run: echo "::set-output name=status::$(curl -i -o/dev/null "%(http_code)\\n" https://downdetector.com"
        if: status != 200 then echo "Down Detector is Down!!"
        if: status == 200 then echo "All is Well"