name: Simple Github Action
on: push
jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello World"
      - name: Environments Check
        run: |
          node -v
          npm -v

